# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200505_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveyType',
            field=models.CharField(default='feedback', max_length=9000),
            preserve_default=False,
        ),
    ]
